# Generated by Django 4.2.7 on 2025-10-28 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ref', models.CharField(help_text='Human-friendly loan reference', max_length=50, unique=True)),
                ('loan_number', models.CharField(max_length=50, unique=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_disbursed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('principal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_type', models.CharField(choices=[('Flat', 'Flat Rate'), ('Reducing', 'Reducing Balance')], default='Reducing', max_length=20)),
                ('duration_months', models.IntegerField()),
                ('tenure_months', models.IntegerField(blank=True, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('pending_disbursement', 'Pending Disbursement'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('closed', 'Closed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('written_off', 'Written Off'), ('defaulted', 'Defaulted')], default='pending_approval', max_length=20)),
                ('purpose', models.TextField()),
                ('collateral', models.TextField(blank=True)),
                ('guarantors', models.TextField(blank=True)),
                ('repayment_schedule', models.JSONField(blank=True, help_text='Amortization schedule', null=True)),
                ('repay_via_mobile_money', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('written_off_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('ProcessingFee', 'Processing Fee'), ('LatePenalty', 'Late Payment Penalty'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Charge',
                'verbose_name_plural': 'Loan Charges',
            },
        ),
        migrations.CreateModel(
            name='LoanCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('GroupGuarantee', 'Group Guarantee'), ('MovableAsset', 'Movable Asset'), ('TitleDeed', 'Title Deed'), ('Vehicle', 'Vehicle'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Collateral',
                'verbose_name_plural': 'Loan Collaterals',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('applied_to_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('applied_to_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('applied_to_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('mobile_money_tx_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('running_outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_repayments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_type', models.CharField(choices=[('Flat', 'Flat Rate'), ('Reducing', 'Reducing Balance')], default='Reducing', max_length=20)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_duration_months', models.IntegerField()),
                ('min_duration_months', models.IntegerField()),
                ('grace_period_months', models.IntegerField(default=0)),
                ('allow_partial_disbursement', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sacco')),
            ],
        ),
    ]
