# Generated by Django 4.2.7 on 2025-10-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_ref',
            field=models.CharField(blank=True, help_text='Human-friendly loan reference', max_length=50, null=True, unique=True),
        ),
    ]
