# Generated by Django 4.2.7 on 2025-10-29 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0003_alter_loan_loan_number_alter_loan_loan_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
