# Generated by Django 4.2.7 on 2025-10-28 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('home_address', models.TextField()),
                ('village_town', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('subcounty', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Prospect', 'Prospect')], default='Active', max_length=20)),
                ('date_joined', models.DateField()),
                ('shares_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('business_registration_status', models.CharField(choices=[('Registered', 'Registered'), ('Informal', 'Informal'), ('None', 'None')], default='Informal', max_length=20)),
                ('autonomy_score', models.IntegerField(default=5, help_text='Score 0-10 for member autonomy/empowerment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('InApp', 'In-App'), ('Push', 'Push Notification')], default='InApp', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_complete', models.BooleanField(default=False)),
                ('additional_documents', models.JSONField(blank=True, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_location', models.CharField(blank=True, max_length=200, null=True)),
                ('years_in_business', models.IntegerField(blank=True, null=True)),
                ('monthly_business_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('family_size', models.IntegerField(default=1)),
                ('education_level', models.CharField(choices=[('None', 'None'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('University', 'University')], default='Primary', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
        migrations.CreateModel(
            name='MemberGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('meeting_frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly')], default='Monthly', max_length=20)),
                ('social_fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('group_guarantee_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='members.member')),
                ('members', models.ManyToManyField(blank=True, related_name='member_groups', to='members.member')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sacco')),
            ],
            options={
                'verbose_name': 'Member Group',
                'verbose_name_plural': 'Member Groups',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membergroup'),
        ),
        migrations.AddField(
            model_name='member',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sacco'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(choices=[('ID', 'National ID'), ('Passport', 'Passport'), ('Receipt', 'Receipt'), ('Contract', 'Contract'), ('Other', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MemberMobileWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('Airtel', 'Airtel Money'), ('Equity', 'Equity Bank'), ('Other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_wallets', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Mobile Wallet',
                'verbose_name_plural': 'Member Mobile Wallets',
                'unique_together': {('member', 'provider')},
            },
        ),
    ]
