# Generated by Django 4.2.7 on 2025-10-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('loan_approval', 'Loan Approval'), ('loan_rejection', 'Loan Rejection'), ('loan_disbursement', 'Loan Disbursement'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('member_registration', 'Member Registration'), ('payment_reminder', 'Payment Reminder'), ('password_reset', 'Password Reset'), ('system_alert', 'System Alert'), ('group_contribution', 'Group Contribution'), ('emergency_loan', 'Emergency Loan'), ('training_completion', 'Training Completion')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='members_not_user_id_d52c62_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['action_type'], name='members_not_action__86ddc0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='members_not_sent_at_02725b_idx'),
        ),
    ]
