# Generated by Django 4.2.7 on 2025-10-29 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_notification_action_type_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='application_received_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='application_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='application_received_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='approval_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='approved_by_committee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='attachment_id_copy',
            field=models.FileField(blank=True, null=True, upload_to='members/attachments/'),
        ),
        migrations.AddField(
            model_name='member',
            name='attachment_passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/attachments/'),
        ),
        migrations.AddField(
            model_name='member',
            name='attachment_proof_initial_deposit',
            field=models.FileField(blank=True, null=True, upload_to='members/attachments/'),
        ),
        migrations.AddField(
            model_name='member',
            name='attachment_recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='members/attachments/'),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widow', 'Widow'), ('Divorced', 'Divorced')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_category',
            field=models.CharField(blank=True, choices=[('Ordinary', 'Ordinary Member'), ('Associate', 'Associate Member'), ('Founding', 'Founding Member')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Group', 'Group / Association')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_contribution_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('MobileMoney', 'Mobile Money'), ('Bank', 'Bank Deposit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='referred_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
