# Generated by Django 4.2.7 on 2025-10-28 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('loan_approval', 'Loan Approval'), ('loan_rejection', 'Loan Rejection'), ('loan_disbursement', 'Loan Disbursement'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('member_registration', 'Member Registration'), ('payment_reminder', 'Payment Reminder'), ('password_reset', 'Password Reset'), ('system_alert', 'System Alert'), ('group_contribution', 'Group Contribution'), ('emergency_loan', 'Emergency Loan'), ('training_completion', 'Training Completion')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['action_type'], name='notificatio_action__9d8def_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_265656_idx'),
        ),
    ]
