# Generated by Django 4.2.7 on 2025-10-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_action_type_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('loan_approval', 'Loan Approval'), ('loan_rejection', 'Loan Rejection'), ('loan_disbursement', 'Loan Disbursement'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('member_registration', 'Member Registration'), ('payment_reminder', 'Payment Reminder'), ('loan_overdue', 'Loan Overdue'), ('password_reset', 'Password Reset'), ('system_alert', 'System Alert'), ('group_contribution', 'Group Contribution'), ('emergency_loan', 'Emergency Loan'), ('training_completion', 'Training Completion')], max_length=30, null=True),
        ),
    ]
